version: '3.8'

services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    container_name: mysqlsrv
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=Senha123
    volumes:
      - db:/var/lib/mysql

  registration_app:
    build: ./app/registration
    container_name: registration
    ports:
      - 3333:3333
    volumes:
      - ./app/registration:/usr/app
    links:
      - db
    depends_on:
      - db

volumes:
  db:
    driver: local
